#!/usr/bin/env python3
"""Generate SQL statements (DDL + seed data) from the local SQLite DB.
Output: src/lib/db-init-sql.ts with a JSON array of statements.
Used as runtime DB initializer fallback on Vercel."""
import sqlite3
import json
from datetime import datetime

DB = '/home/z/my-project/db/custom.db'
OUT = '/home/z/my-project/src/lib/db-init-sql.ts'

con = sqlite3.connect(DB)
cur = con.cursor()

stmts = []

# DDL from sqlite_master
for (sql,) in cur.execute(
    "SELECT sql FROM sqlite_master WHERE sql IS NOT NULL AND name NOT LIKE 'sqlite_%' AND type='table' ORDER BY rootpage"
):
    stmts.append(sql.rstrip().rstrip(';') + ';')

# Indexes
for (sql,) in cur.execute(
    "SELECT sql FROM sqlite_master WHERE type='index' AND sql IS NOT NULL"
):
    stmts.append(sql.rstrip().rstrip(';') + ';')

def fmt(v):
    if v is None:
        return 'NULL'
    if isinstance(v, float):
        return repr(v)
    if isinstance(v, int):
        return str(v)
    if isinstance(v, bytes):
        return "X'" + v.hex() + "'"
    if isinstance(v, datetime):
        v = v.isoformat(sep=' ')
    s = str(v).replace("'", "''")
    return "'" + s + "'"

# Data (respect FK order: parents first)
order = ['Room', 'Guest', 'Booking', 'Bill', 'MenuItem', 'FoodOrder', 'OrderItem', 'Staff', 'StaffPayment', 'LedgerEntry', 'User', 'Setting', 'ExpenseCategory', 'AuditLog']
tables = [r[0] for r in cur.execute("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'")]
tables.sort(key=lambda t: order.index(t) if t in order else 99)

for t in tables:
    cols = [r[1] for r in cur.execute(f'PRAGMA table_info("{t}")')]
    rows = cur.execute(f'SELECT * FROM "{t}"').fetchall()
    for row in rows:
        vals = ', '.join(fmt(v) for v in row)
        col_list = ', '.join(f'"{c}"' for c in cols)
        stmts.append(f'INSERT INTO "{t}" ({col_list}) VALUES ({vals});')

con.close()

payload = '// AUTO-GENERATED by scripts/gen-db-sql.py — DDL + seed data for runtime DB init\n'
payload += 'export const DB_STATEMENTS: string[] = ' + json.dumps(stmts, ensure_ascii=False, indent=0) + '\n'

with open(OUT, 'w') as f:
    f.write(payload)

print(f'Generated {len(stmts)} statements -> {OUT}')
